server:
  port: 7001

eureka:
  instance:
    hostname: localhost  #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不将自己注册到eureka
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护注册中心不需要去检索服务
    service-url:
      #设置与eureka交互的地址，查询服务和注册服务都需要依赖这个地址
      defultZone: http://${eureka.instance.hostname}:${server.port}/eureka/