server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    #true表示将自己注册到注册中心
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认是true，单节点无所谓，集群必须设置为true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true